Argus.MVC/Models/ApplicationModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Argus.MVC.Models
{
	/// <summary>
	/// An aggregation of a company application and issue data
	/// for the reporting dashboard.
	/// </summary>
	public class ApplicationModel
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public int IssueCount { get; set; }
		public bool HasUrgentPriority { get; set; }
		public string ProductOwnerName { get; set; }
		public string TeamName { get; set; }
		public string Url { get; set; }
	}
}

Argus.MVC/Models/ErrorViewModel.cs
using System;

namespace Argus.MVC.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Argus.MVC/Controllers/HomeController.cs
using Argus.Core.Application;
using Argus.Core.Enums;
using Argus.Core.Issue;
using Argus.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Reflection;

namespace Argus.MVC.Controllers
{
	public class HomeController : Controller
	{
		private readonly IConfiguration _config;
		private readonly IApplicationService _applicationService;
		private readonly IIssueService _issueService;
		private readonly ILogger _logger;

		/// <summary>
		/// Default constructor.
		/// </summary>
		/// <param name="config"></param>
		/// <param name="applicationRepo"></param>
		/// <param name="issueRepository"></param>
		/// <remarks>
		///		The repositories are registered as services in Startup.cs, so that's where they come from.
		/// </remarks>
		public HomeController(IConfiguration config, IApplicationService applicationService, IIssueService issueService, ILogger<HomeController> logger)
		{
			_config = config ??
				throw new ArgumentNullException("Configuration cannot be null.");
			_applicationService = applicationService ??
				throw new ArgumentNullException(nameof(applicationService), "Application Service cannot be null.");
			_issueService = issueService ??
				throw new ArgumentNullException(nameof(issueService), "Issue Service cannot be null.");
			_logger = logger;
		}

		public IActionResult Index(int sortOption = 0)
		{
			IEnumerable<ApplicationModel> appsModel = null;

			try
			{
				SortOption sortSelection = GetValidSortOption(sortOption);

				// Get the Font Awesome CDN key from secrets.json.
				ViewBag.FontAwesomeKey = _config.GetValue<string>("fontawesome-cdn-key");
				ViewBag.IssueSubmissionUrl = _config.GetValue<string>("IssueSubmissionUrl");
				ViewBag.SortSelection = (int)sortSelection;

				// Hard-coded date because we'll only have a subset of data for a particular date.
				appsModel = GetApplicationIssues(new DateTime(2019, 6, 6), sortSelection);
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "Error in HomeController.Index()!");
				throw;
			}

			return View(appsModel);
		}

		public IActionResult About(bool showChangeLog = false)
		{
			try
			{
				ViewBag.ShowChangeLog = showChangeLog;
				ViewBag.FontAwesomeKey = _config.GetValue<string>("fontawesome-cdn-key");
				ViewBag.AppVersion = GetAssemblyVersion();
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "Error in HomeController.About()!");
				throw;
			}

			return View();
		}

		public IActionResult NotFound()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			// Consider a middleware option, like so: https://code-maze.com/global-error-handling-aspnetcore/#builtinmiddleware
			var requestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
			var feature = HttpContext.Features.Get<Microsoft.AspNetCore.Diagnostics.IExceptionHandlerFeature>(); // Figure out why this returns null.
			string requestInfo = $"{requestId}: {HttpContext.Request.QueryString}";

			try
			{
				ViewBag.FontAwesomeKey = _config.GetValue<string>("fontawesome-cdn-key");
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "Error in HomeController.About()!");
				throw;
			}

			return View(new ErrorViewModel { RequestId = requestId });
		}

		/// <summary>
		/// Tests writing error messages to a log file via the new middleware class.
		/// Temporary; will be removed later.
		/// </summary>
		/// <returns></returns>
		public IActionResult TestError()
		{
			throw new Exception("TEST ERROR!");
		}

		[HttpGet]
		public IActionResult GetApplicationUpdates(int[] applicationIds, int sortOption = 0, bool isTest = false)
		{
			try
			{
				SortOption sortSelection = GetValidSortOption(sortOption);
				var applications = GetApplicationIssues(new DateTime(2019, 6, 6), sortSelection)
						.Where(a => applicationIds.Contains(a.Id))
						.ToList();

				// Modify some data to test client-side updating, because we have limited data to work with.
				if (isTest && applications?.Count() >= 2)
				{
					applications[0].IssueCount = 3;
					applications[1].IssueCount = 2;
					applications[2].HasUrgentPriority = !applications[2].HasUrgentPriority;
				}

				return Json(applications);
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "Error in HomeController.GetApplicationUpdates()!");
				throw;
			}
		}

		private IEnumerable<ApplicationModel> GetApplicationIssues(DateTime date, SortOption sortSelection = SortOption.Alphabetical)
		{
			var applications = _applicationService.GetApplications()?
				.Where(a => a.IsEnabled == true)
				.OrderBy(a => a.Name);

			var issues = _issueService.GetIssuesByDate(date, date.AddDays(1));

			List<ApplicationModel> appsModel = new List<ApplicationModel>();
			foreach(var application in applications)
			{
				appsModel.Add(new ApplicationModel
				{
					Id = application.Id,
					Name = application.Name,
					IssueCount = issues.Where(i => i.ApplicationId == application.Id).Count(),
					HasUrgentPriority = issues.Any(
						i => i.ApplicationId == application.Id
						&& i.Priority == Priority.Urgent),
					ProductOwnerName = application.ProductOwnerName,
					TeamName = application.TeamName,
					Url = application.Url
				});
			}

			if (sortSelection == SortOption.Priority)
			{
				appsModel = (
					from a in appsModel
					orderby a.HasUrgentPriority descending, a.IssueCount descending, a.Name
					select a
				).ToList();
			}

			return appsModel;
		}

		private SortOption GetValidSortOption(int sortOption)
		{
			SortOption sortSelection = (int)SortOption.Alphabetical;
			sortSelection =
				(SortOption)Enum.GetValues(typeof(SortOption))
					.Cast<int>()
					.FirstOrDefault(o => o == sortOption);

			return sortSelection;
		}

		private string GetAssemblyVersion()
		{
			string appVersionAndMode = string.Format("{0} in {1} mode.",
				Assembly.GetEntryAssembly().GetCustomAttribute<AssemblyInformationalVersionAttribute>().InformationalVersion,
				Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT")?.ToUpper());

			return appVersionAndMode;
		}
	}
}

Argus.MVC/ViewComponents/ChangeLogViewComponent.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Argus.MVC.ViewComponents
{
	public class ChangeLogViewComponent : ViewComponent
	{
		public ChangeLogViewComponent()
		{

		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			string changeLogContent = string.Empty;
			string filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/content/changelog.html");

			using (var reader = File.OpenText(filePath))
			{
				changeLogContent = await reader.ReadToEndAsync();
			}

			return View("Default", changeLogContent);
		}
	}
}

Argus.MVC/Views/Home/About.cshtml
@{
	ViewData["Title"] = "About";
	string fontAwesomeCdnSource = "https://use.fontawesome.com/" + @ViewBag.FontAwesomeKey + ".js";

	string changelogCollapseCss = "collapse";
	if (ViewBag.ShowChangeLog)
	{
		changelogCollapseCss += " show";
	}
}

<script src="@fontAwesomeCdnSource"></script>

<h1>About</h1>
<div>
	<strong>Argus</strong> is an application-monitoring website that periodically checks
	<strong>[Issue-Submission Site]</strong> for open issues for application or website and
	displays any updates in a sleek and mobile-friendly user-interface. It also provides
	links to [Issue-Submission Site] so you can quickly report issues.
</div>
<br />

<div class="accordion" id="accordionExample">
	<div class="card">
		<div class="card-header" id="headingFeatures" data-toggle="collapse" data-target="#collapseFeatures" aria-expanded="true" aria-controls="collapseFeatures">
			<h2 class="mb-0">
				<button class="btn btn-link collapsed" type="button">
					Features
				</button>
			</h2>
		</div>
		<div id="collapseFeatures" class="collapse" aria-labelledby="headingFeatures" data-parent="#accordionExample">
			<div class="card-body">
				<ul>
					<li>
						<strong>Color-Coded UI</strong> - Application cards are color-coded depending on their issue count and urgency.
					</li>
					<li>
						<strong>Toggleable Application Cards</strong> - You can hide (and later show) applications irrelevant to you or your team
						by clicking the <i class="fa fa-eye-slash fa-2 fa-clickable" aria-hidden="true" title="Click to hide this application."></i>
						icon.
					</li>
					<li>
						<strong>Auto-Scroll</strong> - You can select to automatically scroll down the page. (and back up).
					</li>
					<li>
						<strong>Auto-Refresh</strong> - Select this option to have the page periodically refresh its data.
					</li>
					<li>
						<strong>Sorting</strong> - Application sort-order can be toggled between issue <em>priority</em> or <em>alphabetically</em> (default).
					</li>
					<li>
						<strong>Save App Selection</strong> - Click this option and Argus will automatically hide the apps you don't want to see for future visits.
					</li>
					<li>
						<strong>Responsive Design</strong> - The website maintains function and style on both desktop and mobile devices.
					</li>
				</ul>
			</div>
		</div>
	</div>

	<div class="card">
		<div class="card-header" id="headingColorCoding" data-toggle="collapse" data-target="#collapseColorCoding" aria-expanded="false" aria-controls="collapseColorCoding">
			<h2 class="mb-0">
				<button class="btn btn-link collapsed" type="button">
					How The Color-Coding Works
				</button>
			</h2>
		</div>
		<div id="collapseColorCoding" class="collapse" aria-labelledby="headingColorCoding" data-parent="#accordionExample">
			<div class="card-body">
				<p>
					Applications having no reported issues will have their UI elements shaded <span class="text-success">green</span>, while
					those having 1-2 issues are shaded <span class="text-warning">yellow</span>. Applications having 3 or more reported issues
					- or have <em>any</em> number of issues of <b>high priority</b> - will be shaded <span class="text-danger">red</span>.
				</p>
				<p>
					Additionally, applications with any number of high priority issues will be denoted with a
					<i class="fa fa-exclamation-triangle pulse" aria-hidden="true" title="High priority issue(s) have been reported."></i> icon.
				</p>
			</div>
		</div>
	</div>

	<div class="card">
		<div class="card-header" id="headingChangelog" data-toggle="collapse" data-target="#collapseChangelog" aria-expanded="@(ViewBag.ShowChangeLog)" aria-controls="collapseChangelog">
			<h2 class="mb-0">
				<button class="btn btn-link collapsed" type="button">
					Changelog
				</button>
			</h2>
		</div>
		<div id="collapseChangelog" class="@(changelogCollapseCss)" aria-labelledby="headingChangelog" data-parent="#accordionExample">
			<div class="card-body">
				@await Component.InvokeAsync("ChangeLog")
			</div>
		</div>
	</div>

	<div class="card">
		<div class="card-header" id="headingName" data-toggle="collapse" data-target="#collapseName" aria-expanded="false" aria-controls="collapseName">
			<h2 class="mb-0">
				<button class="btn btn-link collapsed" type="button">
					The Name
				</button>
			</h2>
		</div>
		<div id="collapseName" class="collapse" aria-labelledby="headingName" data-parent="#accordionExample">
			<div class="card-body">
				<strong>Argus</strong> is named after <em>Argus Panoptes</em>, the many-eyed giant of Greek mythology tasked with guarding Io by the goddess Hera,
				from whom the phrase <em><q cite="https://en.wikipedia.org/wiki/Argus_Panoptes">the eyes of Argus</q></em> derives.
				<em>Panoptes</em> translates to "the all-seeing", though apparently not in a premonitory sense, as in an ironic twist of fate
				<span class="spoiler">Argus is slain by the Olympian messenger Hermes after being lulled into a deep sleep.</span>
			</div>
		</div>
	</div>

	<div class="card">
		<div class="card-header" id="headingTechnical" data-toggle="collapse" data-target="#collapseTechnical" aria-expanded="false" aria-controls="collapseTechnical">
			<h2 class="mb-0">
				<button class="btn btn-link collapsed" type="button">
					Technical
				</button>
			</h2>
		</div>
		<div id="collapseTechnical" class="collapse" aria-labelledby="headingTechnical" data-parent="#accordionExample">
			<div class="card-body">
				<p>
					App version: @ViewBag.AppVersion
				</p>
				<strong>Argus</strong> is built with the following:
				<p>
					<ul>
						<li>ASP.NET Core 2.2 MVC</li>
						<li>Bootstrap 4</li>
						<li>C#</li>
						<li>Dapper 1.60</li>
						<li>jQuery 3.3.1</li>
						<li>Moq 4.11</li>
					</ul>
				</p>
			</div>
		</div>
	</div>

	<div class="card">
		<div class="card-header" id="headingContact" data-toggle="collapse" data-target="#collapseContact" aria-expanded="false" aria-controls="collapseContact">
			<h2 class="mb-0">
				<button class="btn btn-link collapsed" type="button">
					Contact
				</button>
			</h2>
		</div>
		<div id="collapseContact" class="collapse" aria-labelledby="headingContact" data-parent="#accordionExample">
			<div class="card-body">
				<ul>
					<li><a href="mailto:jordon.malm@gmail.com" target="_top">Jordon Malm</a>, Software Developer</li>
				</ul>
			</div>
		</div>
	</div>
</div>

Argus.MVC/Views/Home/Index.cshtml
@model IEnumerable<Argus.MVC.Models.ApplicationModel>

@{
	ViewData["Title"] = "Home";
	string fontAwesomeCdnSource = "https://use.fontawesome.com/" + @ViewBag.FontAwesomeKey + ".js";
}

@section Scripts
{
	<script src="@Url.Content("~/js/site.js")"></script>
}

<script>
	var sortOption = localStorage.getItem('sortOption');
	if (sortOption && window.location.href.indexOf("sortOption") == -1) {
		window.location.href = location.origin + '?sortOption=' + sortOption;
	}
</script>

<script src="@fontAwesomeCdnSource"></script>

<div class="text-center">
	<h1 class="display-4">
		<strong>Argus</strong> - System Monitor
		<environment include="Development">
			<strong>(DEV)</strong>
		</environment>
	</h1>
	<p>Status as of <span id="StatusDateTime">@DateTime.Now</span>.</p>

	@await Html.PartialAsync("_ChangelogUpdatePartial")

	<div id="AfterHoursAlert" class="alert alert-warning alert-dismissible" role="alert">
		<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
		NOTE: Auto-refresh is disabled between 6pm and 8am local time! You may still refresh data by reloading the page on-demand.
		<button type="button" class="close" data-dismiss="alert">&times;</button>
	</div>
</div>

<div class="row">
	@* Static card to illustrate issue-free application. *@
	<div class="col-sm-4">
		<div class="card mb-3">
			<h5 class="card-header text-white bg-success">
				Application 0
				<i class="fa fa-eye-slash fa-2 fa-clickable float-right" aria-hidden="true"></i>
			</h5>
			<div class="card-body">
				<p>
					<span class="font-weight-bold">Product Owner: </span>
					Beth Smith
					<br />
					<span class="font-weight-bold">Team: </span>
					Team_5
				</p>
				<button type="button" class="btn btn-block bg-success text-white rounded-pill">
					Reports <span class="badge badge-light">0</span>
				</button>
				<a href="#" class="btn btn-block btn-success rounded-pill">Report a problem</a>
			</div>
		</div>
	</div>

	@foreach (var app in Model)
	{
		string cssClassByIssueCount = "bg-success";
		string cssTextColor = "text-white";

		if (app.HasUrgentPriority || app.IssueCount >= 3)
		{
			cssClassByIssueCount = "bg-danger";
		}
		else if (app.IssueCount >= 1)
		{
			cssClassByIssueCount = "bg-warning";
			cssTextColor = "text-dark";
		}

		<div class="col-sm-4" data-id="@app.Id">
			<div class="card mb-3">
				<h5 class="card-header @cssTextColor @cssClassByIssueCount">
					@app.Name
					@if (app.HasUrgentPriority)
					{
						<i class="fa fa-exclamation-triangle pulse" aria-hidden="true" title="High priority issue(s) have been reported."></i>
					}
					<i class="fa fa-eye-slash fa-2 fa-clickable float-right" aria-hidden="true" title="Click to hide this application."></i>
				</h5>
				<div class="card-body">
					<p class="card-text">
						<span class="font-weight-bold">Product Owner: </span>
						@app.ProductOwnerName
						<br />
						<span class="font-weight-bold">Team: </span>
						@app.TeamName
					</p>
					<button type="button" class="btn btn-block @cssClassByIssueCount @cssTextColor rounded-pill">
						Reports <span class="badge badge-light">@app.IssueCount</span>
					</button>
					<button type="button" class="btn btn-block @cssClassByIssueCount @cssTextColor rounded-pill" onclick="showReportIssueModal()">
						Report a problem
					</button>
				</div>
			</div>
		</div>
	}
</div>

<!-- Loading Modal -->
<div class="modal fade" id="loadingModal" data-backdrop="static">
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content">

			<div class="modal-header bg-primary text-light">
				<h4 class="modal-title">Loading</h4>
				<button type="button" class="close text-light" data-dismiss="modal">&times;</button>
			</div>

			<div class="modal-body">
				<div class="d-flex align-items-center">
					<div class="spinner-border text-primary" role="status" aria-hidden="true"></div>
					<strong class="m-3">Retrieving application updates...</strong>
				</div>
			</div>

			<div class="modal-footer">
			</div>

		</div>
	</div>
</div>

<!-- Settings Modal -->
<div class="modal fade" id="settingsModal">
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content">

			<div class="modal-header bg-primary text-light">
				<h4 class="modal-title">Settings</h4>
				<button type="button" class="close text-light" data-dismiss="modal">&times;</button>
			</div>

			<div class="modal-body">
				<div class="align-items-center">
					<div id="SaveSettingsAlert" class="alert alert-success alert-dismissible" role="alert">
						<i class="fa fa-check-circle-o" aria-hidden="true"></i>
						Your settings have been saved!
						<button type="button" class="close" data-dismiss="alert">&times;</button>
					</div>
					<div id="ResetSettingsAlert" class="alert alert-info alert-dismissible" role="alert">
						<i class="fa fa-info-circle" aria-hidden="true"></i>
						Your settings have been reset!
						<button type="button" class="close" data-dismiss="alert">&times;</button>
					</div>
					<div class="custom-control custom-switch">
						<input id="AutoScrollCheckbox" type="checkbox" class="custom-control-input">
						<label class="custom-control-label" for="AutoScrollCheckbox">Enable auto-scroll</label>
					</div>
					<div class="custom-control custom-switch">
						<input id="AutoRefreshCheckbox" type="checkbox" class="custom-control-input">
						<label class="custom-control-label" for="AutoRefreshCheckbox">Enable auto-refresh</label>
					</div>
					<div class="custom-control custom-switch">
						<input id="UnhideCheckbox" type="checkbox" class="custom-control-input">
						<label class="custom-control-label" for="UnhideCheckbox">Show hidden apps</label>
					</div>
					<div class="dropdown-divider"></div>
					<div class="input-group mb-3">
						<div class="input-group-prepend">
							<label class="input-group-text" for="inputGroupSelect01">Sort</label>
						</div>
						<select class="custom-select" id="SortSelectionInputGroup">
							@* I don't like this but at least it's clean enough to read. *@
							@if (ViewBag.SortSelection == 1)
							{
							<option value="0">Alphabetical (default)</option>
							<option value="1" selected>Priority</option>
							}
							else
							{
							<option value="0" selected>Alphabetical (default)</option>
							<option value="1">Priority</option>
							}
						</select>
					</div>

				</div>
			</div>

			<div class="modal-footer justify-content-center">
				<button class="btn btn-primary rounded-pill" href="#" onclick="saveSettings()">
					<span><i class="fa fa-floppy-o" aria-hidden="true"></i></span>
					<span class="pl-2">Save Settings</span>
				</button>
				<button class="btn btn-danger rounded-pill" href="#" onclick="resetSettings()">
					<span><i class="fa fa-floppy-o" aria-hidden="true"></i></span>
					<span class="pl-2">Reset Settings</span>
				</button>
			</div>

		</div>
	</div>
</div>

<!-- Report-An-Issue Modal -->
<div class="modal fade" id="reportIssueModal">
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content">

			<div class="modal-header bg-primary text-light">
				<h4 class="modal-title">Report Issue</h4>
				<button type="button" class="close text-light" data-dismiss="modal">&times;</button>
			</div>

			<div class="modal-body">
				<div class="align-items-center">
					<p>
						Click below to go to <strong>[Issue-Submission Site]</strong>
						in a new browser tab and submit your issue.
					</p>
					<p>
						<strong>Argus</strong> looks at a few things when reporting data. To maximize its effectiveness,
						please <em>tag</em> your issue with the appropriate application keyword(s) and/or include the
						the application's name in the title.
					</p>
					<p>
						<img src="" alt="Image showing how to tag keywords" height="42" width="42">
					</p>
				</div>
			</div>

			<div class="modal-footer">
				<a href="@ViewBag.IssueSubmissionUrl" target="_blank" class="btn btn-block btn-primary rounded-pill">Go to [Issue-Submission Site]!</a>
			</div>

		</div>
	</div>
</div>

Argus.MVC/Views/Home/NotFound.cshtml
@{
	ViewData["Title"] = "Not Found";
}

<h1>Not Found</h1>
<p>
	We couldn't find what you're looking for!
</p>
<div>
	<a class="btn btn-primary rounded-pill" asp-controller="Home" asp-action="Index">Go Home</a>
</div>

Argus.MVC/Views/Shared/Components/ChangeLog/Default.cshtml
@model string

<div>
	@Html.Raw(Model)
</div>

Argus.MVC/Views/Shared/_ChangelogUpdatePartial.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
	string latestAppVersion = typeof(Argus.MVC.Controllers.HomeController).Assembly.GetName().Version.ToString();
	var userAppVersion = HttpContextAccessor.HttpContext.Request.Cookies["userAppVersion"];
	//var cookies = HttpContextAccessor.HttpContext.Request.Cookies;

	bool showChangelogAlert = !string.Equals(userAppVersion, latestAppVersion, StringComparison.InvariantCultureIgnoreCase);
}

@if (showChangelogAlert)
{
	<div id="ChangelogUpdateAlert" class="alert alert-primary alert-dismissible" role="alert">
		<i class="fa fa-exclamation-circle" aria-hidden="true"></i>
		Welcome to Argus <b>@($"v{latestAppVersion}!")</b> See what's new in the
		<a asp-area="" asp-controller="Home" asp-action="About" asp-route-showChangeLog="true" class="font-weight-bold">Changelog</a>.
		<button type="button" class="close" data-dismiss="alert">&times;</button>
	</div>

	<script>
		window.onload = function () {
			$('#ChangelogUpdateAlert').on('closed.bs.alert', function () {
				document.cookie = 'userAppVersion=' + '@latestAppVersion';
			});
		};
	</script>
}

Argus.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>Argus - @ViewData["Title"]</title>

	<environment include="Development">
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
	</environment>
	<environment exclude="Development">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
			  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
			  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
			  crossorigin="anonymous"
			  integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
	</environment>
	<link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm fixed-top navbar-dark bg-primary text-light mb-3 justify-content-center">
			<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Company_Name</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
					aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
				<ul class="navbar-nav flex-grow-1">
					<li class="nav-item">
						<a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" asp-area="" asp-controller="Home" asp-action="About">About</a>
					</li>
					@if (Url.ActionContext.RouteData.Values["action"].ToString().Equals("Index", StringComparison.InvariantCultureIgnoreCase))
					{
						<li class="nav-item">
							@* This omits the anchor and avoids its URL messiness. *@
							<a id="settingsLink" class="nav-link" href="javascript:void(0)">
								Settings
							</a>
						</li>
					}
				</ul>
			</div>
		</nav>
	</header>
	<main role="main" class="container pb-3">
		<partial name="_CookieConsentPartial" />
		@RenderBody()
	</main>

	<footer class="border-top footer bg-primary text-light">
		<div class="text-center">
			&copy; @DateTime.Now.Year - Company_Name
		</div>
	</footer>

	<environment include="Development">
		<script src="~/lib/jquery/dist/jquery.js"></script>
		<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
	</environment>
	<environment exclude="Development">
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
				asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
				asp-fallback-test="window.jQuery"
				crossorigin="anonymous"
				integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
		</script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
				asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
				asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
				crossorigin="anonymous"
				integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
		</script>
	</environment>

	@RenderSection("Scripts", required: false)
</body>
</html>